### ISSUE TITLE
Panic: Can't set rate

### ISSUE THREAD

**Issue by joleeee** [not-fl3/quad-snd#45]
Just tried running some of the *macroquad* examples, but the audio thread paniced. I get the same error just trying the examples here.

```sh
$ cargo run --example simple
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/simple`
thread '<unnamed>' panicked at 'Can't set rate.', src/alsa_snd.rs:57:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Audio thread died
Audio thread died
```

backtrace:
```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/6dba4ed215e7a60f0a2a19c04f3f73691f89c509/library/std/src/panicking.rs:616:12
   1: quad_snd::snd::setup_pcm_device
             at ./src/alsa_snd.rs:57:9
   2: quad_snd::snd::audio_thread
             at ./src/alsa_snd.rs:104:22
   3: quad_snd::snd::AudioContext::new::{{closure}}
             at ./src/alsa_snd.rs:160:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by joleeee** [comment]
Should've added: I'm on Artix Linux, kernel 5.18.12. I use pipewire, pipewire-pulse and wireplumber.

I guess the configuration space is empty? I don't know what this means.
https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html#ga39124280d06ce63092a77e3f25ddd6ee

**Comment by joleeee** [comment]
installing pipewire-alsa fixed it, at least someone else can google the error if they encounter the same issue

nice rickroll :smiling_face_with_tear:
